Update maven-publish.yml

diff --git a/.github/workflows/maven-publish.yml b/.github/workflows/maven-publish.yml
--- a/.github/workflows/maven-publish.yml
+++ b/.github/workflows/maven-publish.yml
@@ -42,18 +42,18 @@ jobs:
           mvn versions:set -DnewVersion=${{ env.VERSION }} -DgenerateBackupPoms=false
           mvn versions:commit
           
-      - name: List Secrets
-        run: gpg --list-secret-keys --keyid-format LONG
+#      - name: List Secrets
+#        run: gpg --list-secret-keys --keyid-format LONG
 
-      - name: Debug github.workspace
-        run: |
-          echo "github.workspace is: ${{ github.workspace }}"
-          ls -la ${{ github.workspace }}
-
-      - name: Dump settings.xml contents
-        run: |
-          echo "Dumping contents of settings.xml:"
-          cat ${{ github.workspace }}/settings.xml || echo "settings.xml not found!"
+#      - name: Debug github.workspace
+#        run: |
+#          echo "github.workspace is: ${{ github.workspace }}"
+#          ls -la ${{ github.workspace }}
+#
+#      - name: Dump settings.xml contents
+#        run: |
+#          echo "Dumping contents of settings.xml:"
+#          cat ${{ github.workspace }}/settings.xml || echo "settings.xml not found!"
 
       - name: Deploy to Maven Central
         env:
